# Generated by Django 3.2.4 on 2021-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='kota',
        ),
        migrations.AddField(
            model_name='company',
            name='kabupaten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='kecamatan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='kelurahan',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Kota',
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
    ]
