# Generated by Django 4.1.7 on 2023-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="service",
            name="province",
            field=models.CharField(max_length=255),
        ),
    ]
