# Generated by Django 3.2.4 on 2021-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210630_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='kabupaten',
            new_name='kabupaten_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='kecamatan',
            new_name='kecamatan_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='kelurahan',
            new_name='kelurahan_id',
        ),
        migrations.AddField(
            model_name='company',
            name='kabupaten_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kecamatan_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kelurahan_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
