# Generated by Django 4.1.7 on 2024-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_servicecategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ServiceStatus",
        ),
    ]
