# Generated by Django 3.2.4 on 2021-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kabupaten_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='kabupaten_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='kecamatan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='kecamatan_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='kelurahan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='kelurahan_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
