# Generated by Django 4.1.7 on 2024-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_service_is_open_delete_servicestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicequeue",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
