# Generated by Django 3.2.4 on 2021-08-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210713_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
