# Generated by Django 4.1.7 on 2024-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_servicequeue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
