# Generated by Django 3.2.4 on 2021-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='kota',
            new_name='kabupaten',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kecamatan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kelurahan',
            field=models.IntegerField(default=0),
        ),
    ]
