# Generated by Django 4.1.7 on 2023-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0002_alter_userprofile_city_alter_userprofile_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
