# Generated by Django 4.1.7 on 2023-12-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0003_remove_userprofile_name_alter_userprofile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
