# Generated by Django 4.1.7 on 2023-12-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0007_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
