# Generated by Django 4.1.7 on 2024-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0008_remove_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.BooleanField(default=False),
        ),
    ]
