# Generated by Django 4.1.7 on 2024-02-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0009_userprofile_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_type",
            new_name="is_owner",
        ),
    ]
